# Generated by Django 4.1.2 on 2022-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cedva1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='convenio',
            field=models.CharField(choices=[('p', 'Seleccione opción'), ('SI', 'Si'), ('NO', 'No')], default='p', max_length=800),
        ),
    ]
